# Generated by Django 3.0.6 on 2023-02-10 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(blank=True, max_length=100)),
                ('answer_2', models.CharField(blank=True, max_length=100)),
                ('answer_3', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_title', models.CharField(max_length=100)),
                ('answer_1', models.CharField(blank=True, max_length=100)),
                ('answer_2', models.CharField(blank=True, max_length=100)),
                ('answer_3', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_4', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_type', models.CharField(blank=True, choices=[('Custom Question', 'Custom Question'), ('Yes / No Question', 'Yes / No Question')], max_length=100)),
                ('slug', models.SlugField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=250)),
                ('last_name', models.CharField(default='', max_length=250)),
                ('email_address', models.CharField(default='', max_length=250)),
                ('mobile_number', models.CharField(default='', max_length=250)),
                ('display_picture', models.ImageField(default='', upload_to='Display Picture')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnswerSurvey')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.CreateSurvey')),
            ],
        ),
    ]
