# Generated by Django 3.0.6 on 2023-02-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230210_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersurvey',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='answersurvey',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='answersurvey',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='answersurvey',
            name='answer_4',
        ),
        migrations.AddField(
            model_name='answersurvey',
            name='answer',
            field=models.ManyToManyField(related_name='asnwers', to='core.CreateSurvey'),
        ),
        migrations.RemoveField(
            model_name='polls',
            name='answer_to',
        ),
        migrations.AddField(
            model_name='polls',
            name='answer_to',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.AnswerSurvey'),
            preserve_default=False,
        ),
    ]
