# Generated by Django 3.0.6 on 2023-02-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230210_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(blank=True, max_length=100)),
                ('answer_2', models.CharField(blank=True, max_length=100)),
                ('answer_3', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='answersurvey',
            name='answer',
            field=models.ManyToManyField(related_name='options', to='core.Options'),
        ),
    ]
