# Generated by Django 3.0.6 on 2023-02-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230210_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='polls',
            name='answer_to',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='survey',
        ),
        migrations.RenameModel(
            old_name='Options',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='CreateSurvey',
            new_name='Poll',
        ),
        migrations.DeleteModel(
            name='AnswerSurvey',
        ),
        migrations.DeleteModel(
            name='Polls',
        ),
        migrations.AddField(
            model_name='vote',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='core.Poll'),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='core.Choice'),
        ),
    ]
