# Generated by Django 3.0.6 on 2023-02-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230210_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='answer_1',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='answer_4',
        ),
    ]
