# Generated by Django 3.0.6 on 2023-02-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230210_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='answer',
            new_name='survey_title',
        ),
        migrations.AddField(
            model_name='choice',
            name='survey_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Poll'),
        ),
    ]
