# Generated by Django 3.0.6 on 2023-02-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230210_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='answer',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='survey_title',
        ),
    ]
