# Generated by Django 3.2.5 on 2023-02-23 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230223_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='survey_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.poll'),
        ),
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
