# Generated by Django 3.2.5 on 2023-02-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230223_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='first_choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='fourth_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='second_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='third_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
