# Generated by Django 3.2.5 on 2023-02-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230223_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='first_choice',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='fourth_choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='second_choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='third_choice',
        ),
    ]
