# Generated by Django 3.2.5 on 2023-02-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230223_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_choice', models.CharField(blank=True, max_length=100)),
                ('second_choice', models.CharField(blank=True, max_length=100)),
                ('third_choice', models.CharField(blank=True, max_length=100)),
                ('fourth_choice', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
